name: Org CI Workflow

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.2'
      node-version:
        required: false
        type: string
        default: '18'

jobs:
  backend-tests:
    name: Laravel Backend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, bcmath, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Pint + PHPUnit
        run: |
          set +e
          vendor/bin/pint --test 2>&1 | tee backend.log
          php artisan test --parallel --stop-on-failure 2>&1 | tee -a backend.log
          set -e

      - name: Upload backend log
        uses: actions/upload-artifact@v4
        with:
          name: backend-log
          path: backend.log

  frontend-tests:
    name: React/Expo Frontend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint + Prettier + Tests
        run: |
          set +e
          npm run lint --if-present 2>&1 | tee frontend.log
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}" 2>&1 | tee -a frontend.log
          npm test --if-present -- --watchAll=false 2>&1 | tee -a frontend.log
          set -e

      - name: Upload frontend log
        uses: actions/upload-artifact@v4
        with:
          name: frontend-log
          path: frontend.log

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: always()
    steps:
      - name: Download backend logs
        uses: actions/download-artifact@v4
        with:
          name: backend-log
          path: logs

      - name: Download frontend logs
        uses: actions/download-artifact@v4
        with:
          name: frontend-log
          path: logs

      - name: Send notification to Discord
        run: |
          BACKEND_LOG=$(tail -n 30 logs/backend.log 2>/dev/null || echo "No backend logs")
          FRONTEND_LOG=$(tail -n 30 logs/frontend.log 2>/dev/null || echo "No frontend logs")

          BACKEND_LOG=$(echo "$BACKEND_LOG" | jq -Rs .)
          FRONTEND_LOG=$(echo "$FRONTEND_LOG" | jq -Rs .)

          STATUS="✅ Success"
          if [ "${{ needs.backend-tests.result }}" != "success" ] || [ "${{ needs.frontend-tests.result }}" != "success" ]; then
            STATUS="❌ Failed"
          fi

          curl -X POST "https://0f02abcb3950.ngrok-free.app/github" \
          -H "Content-Type: application/json" \
          -d "{
            \"status\": \"$STATUS\",
            \"repo\": \"${{ github.repository }}\",
            \"run_id\": \"${{ github.run_id }}\",
            \"pr\": \"${{ github.event.pull_request.number }}\",
            \"backend_log\": $BACKEND_LOG,
            \"frontend_log\": $FRONTEND_LOG
          }"
