name: Org CI Workflow

on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP version to use"
        required: false
        type: string
        default: '8.2'

jobs:
  laravel-tests:
    name: Laravel Pint + PHPUnit
    runs-on: ubuntu-latest
    outputs:
      log: ${{ steps.logs.outputs.cleaned_log }}
      result: ${{ steps.set-result.outputs.job_result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, bcmath, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Pint
        id: pint
        continue-on-error: true
        run: vendor/bin/pint --test 2>&1 | tee pint.log

      # - name: Run PHPUnit
      #   id: phpunit
      #   continue-on-error: true
      #   run: php artisan test --parallel --stop-on-failure 2>&1 | tee phpunit.log
        
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install JS dependencies
        run: npm install
        
      - name: Run Prettier (check only)
        id: prettier
        continue-on-error : true
        run: |
          npx prettier --check . 2>&1 | tee -a test.log
          
      - name: Run ESLint
        id: ESLint
        continue-on-error : true
        run: |
          npx eslint . --max-warnings=0 2>&1 | tee -a test.log
          
      - name: Merge logs
        run: cat pint.log phpunit.log > test.log

      - name: Save last 30 lines of log
        id: logs
        run: |
          TAIL_LOG=$(tail -n 30 test.log 2>/dev/null || echo "No logs")
          CLEAN_LOG=$(echo "$TAIL_LOG" | jq -Rs .)
          echo "cleaned_log=$CLEAN_LOG" >> $GITHUB_OUTPUT

      - name: Set final result
        id: set-result
        run: |
          if [ "${{ steps.pint.outcome }}" = "failure" ] || [ "${{ steps.phpunit.outcome }}" = "failure" ]; then
            echo "job_result=failure" >> $GITHUB_OUTPUT
          else
            echo "job_result=success" >> $GITHUB_OUTPUT
          fi

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    if: always()
    steps:
      - name: Send notification to Discord
        run: |
          BACKEND="${{ needs.laravel-tests.outputs.result }}"
          STATUS="✅ Success"
          if [ "$BACKEND" != "success" ]; then
            STATUS="❌ Failed"
          fi

          BACKEND_LOG='${{ needs.laravel-tests.outputs.log }}'
          if [ -z "$BACKEND_LOG" ]; then
            BACKEND_LOG="\"\""
          fi

          curl -X POST "https://0f02abcb3950.ngrok-free.app/github" \
          -H "Content-Type: application/json" \
          -d "{
            \"status\": \"$STATUS\",
            \"repo\": \"${{ github.repository }}\",
            \"run_id\": \"${{ github.run_id }}\",
            \"pr\": \"${{ github.event.pull_request.number }}\",
            \"backend\": \"$BACKEND\",
            \"backend_log\": $BACKEND_LOG
          }"
