name: Org CI Workflow

on:
  repository_dispatch:
    types: [trigger-org-ci]

jobs:
  laravel-tests:
    name: Laravel Pint + PHPUnit
    runs-on: ubuntu-latest
    outputs:
      log: ${{ steps.logs.outputs.cleaned_log }}
      result: ${{ steps.set-result.outputs.job_result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.client_payload.php_version }}
          extensions: mbstring, bcmath, intl

      - name: Install Composer dependencies
        id: composer
        continue-on-error: true
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Pint
        id: pint
        continue-on-error: true
        run: vendor/bin/pint --test 2>&1 | tee -a test.log
          
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install JS dependencies
        continue-on-error: true
        run: npm install
          
      - name: Run Prettier (check only)
        id: prettier
        continue-on-error: true
        run: npx prettier --check . 2>&1 | tee -a test.log
          
      - name: Run ESLint
        id: ESLint
        continue-on-error: true
        run: npx eslint . --max-warnings=0 2>&1 | tee -a test.log
          
      - name: Save last 30 lines of log
        id: logs
        run: |
          TAIL_LOG=$(tail -n 30 test.log 2>/dev/null || echo "No logs")
          CLEAN_LOG=$(echo "$TAIL_LOG" | jq -Rs .)
          echo "cleaned_log=$CLEAN_LOG" >> $GITHUB_OUTPUT

      - name: Set final result
        id: set-result
        run: |
          if [ "${{ steps.pint.outcome }}" = "failure" ] || [ "${{ steps.prettier.outcome }}" = "failure" ] || [ "${{ steps.ESLint.outcome }}" = "failure" ]; then
            echo "job_result=failure" >> $GITHUB_OUTPUT
          else
            echo "job_result=success" >> $GITHUB_OUTPUT
          fi

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    if: always()
    steps:
    - name: Debug run
      run: |
        echo "BOT_URL = ${{ secrets.BOT_URL }}"
        echo "BOT_TOKEN = ${{ secrets.BOT_TOKEN }}"
          
    - name: Send notification to Discord
      run: |
          BACKEND="${{ needs.laravel-tests.outputs.result }}"
          STATUS="✅ Success"
          if [ "$BACKEND" != "success" ]; then
            STATUS="❌ Failed"
          fi

          BACKEND_LOG='${{ needs.laravel-tests.outputs.log }}'
          if [ -z "$BACKEND_LOG" ]; then
            BACKEND_LOG="\"\""
          fi

          curl -X POST "${{ secrets.BOT_URL }}" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"status\": \"$STATUS\",
              \"repo\": \"${{ github.event.client_payload.branch_repo }}\",
              \"run_id\": \"${{ github.run_id }}\",
              \"pr\": \"${{ github.event.client_payload.pull_request }}\",
              \"backend\": \"$BACKEND\",
              \"backend_log\": $BACKEND_LOG
            }"
