name: Org CI Workflow

on:
  pull_request:
    paths:
      - '**/*.php'

jobs:
  laravel-pint:
    name: Laravel Pint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Pint
        run: |
          set +e
          vendor/bin/pint --test 2>&1 | tee pint.log
          EXIT_CODE=${PIPESTATUS[0]}
          set -e
          exit $EXIT_CODE

      - name: Save last 30 lines of Pint log
        id: logs
        run: |
          TAIL_LOG=$(tail -n 30 pint.log 2>/dev/null || echo "No pint logs")
          # Escape log for JSON
          CLEAN_LOG=$(echo "$TAIL_LOG" | jq -Rs .)
          echo "LOG=$CLEAN_LOG" >> $GITHUB_ENV

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [laravel-pint]
    if: always()
    steps:
      - name: Send notification to Discord
        run: |
          STATUS="✅ Success"
          if [ "${{ needs.laravel-pint.result }}" != "success" ]; then
            STATUS="❌ Failed"
          fi

          curl -X POST "https://0f02abcb3950.ngrok-free.app/github" \
          -H "Content-Type: application/json" \
          -d "{
            \"status\": \"$STATUS\",
            \"repo\": \"${{ github.repository }}\",
            \"run_id\": \"${{ github.run_id }}\",
            \"pr\": \"${{ github.event.pull_request.number }}\",
            \"backend_log\": $LOG
          }"
