name: Org CI Workflow

on:
  repository_dispatch:
    types: [trigger-org-ci]

jobs:
  laravel-tests:
    name: Laravel PINT + Prettier + ESLint
    runs-on: ubuntu-latest
    outputs:
      log: ${{ steps.logs.outputs.cleaned_log }}
      result: ${{ steps.set-result.outputs.job_result }}
    steps:
    
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.branch_repo }}
          ref: refs/pull/${{ github.event.client_payload.pull_request }}/merge
          token: ${{ secrets.PAT_FOR_ORG_REPOS }}
          path: project 
          
      - name: Create log file
        run: touch test.log
        working-directory: project

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.client_payload.php_version }}
          extensions: mbstring, bcmath, intl


      - name: Install Composer dependencies
        id: composer
        continue-on-error: true
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: project

      - name: Run PINT
        id: pint
        continue-on-error: true
        run: vendor/bin/pint --test 2>&1 | tee -a test.log
        working-directory: project

      - name: Setup Node.js
        uses: actions/setup-node@v4


      - name: Install JS dependencies
        continue-on-error: true
        run: npm install
        working-directory: project


      - name: Run Prettier
        id: prettier
        continue-on-error: true
        run: npx prettier --write resources/ 2>&1 | tee -a test.log
        working-directory: project

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: npx eslint resources/ --max-warnings=0 2>&1 | tee -a test.log
        working-directory: project

      - name: Save last 30 lines of log
        id: logs
        run: |
          if [ -f test.log ]; then
            LOG_CONTENT=$(tail -n 30 test.log)
          else
            LOG_CONTENT="No logs"
          fi

          echo "cleaned_log<<EOF" >> "$GITHUB_OUTPUT"
          echo "$LOG_CONTENT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

    
      - name: Set final result
        id: set-result
        run: |
          if [ "${{ steps.pint.outcome }}" = "failure" ] || \
             [ "${{ steps.prettier.outcome }}" = "failure" ] || \
             [ "${{ steps.eslint.outcome }}" = "failure" ]; then
            echo "job_result=failure" >> $GITHUB_OUTPUT
          else
            echo "job_result=success" >> $GITHUB_OUTPUT
          fi


  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    if: always()
    steps:
      - name: Debug run
        run: |
          echo "BOT_URL = ${{ secrets.BOT_URL }}"
          echo "BOT_TOKEN = ${{ secrets.BOT_TOKEN }}"

      - name: Send notification to Discord
        run: |
          PAYLOAD=$(jq -n \
          --arg repo "${{ github.event.client_payload.branch_repo }}" \
          --arg run_id "${{ github.run_id }}" \
          --arg pr "${{ github.event.client_payload.pull_request }}" \
          --arg pint "${{ needs.laravel-tests.result }}" \
          --arg prettier "${{ needs.laravel-tests.result }}" \
          --arg eslint "${{ needs.laravel-tests.result }}" \
          --arg backend_log "${{ needs.laravel-tests.outputs.log }}" \
          '{
            "repo": $repo,
            "run_id": $run_id,
            "pr": $pr,
            "PINT": $pint,
            "Prettier": $prettier,
            "ESLint": $eslint,
            "backend_log": $backend_log
          }')
    
          curl -X POST "${{ secrets.BOT_URL }}" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
